set_property SRC_FILE_INFO {cfile:D:/pablo/Desktop/MIS_APUNTES/Mis_repositorios/Artix7/project_1/project_1.srcs/constrs_1/new/pinesProject1.xdc rfile:../../../project_1.srcs/constrs_1/new/pinesProject1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports clk]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports led]
